version: '3'

volumes:
  portainer_data:
  redis_data:
  ebusrt_data:

services:
#  ebusrt-caller:
#    build: ebusrt-caller
#    volumes:
#     - /tmp:/tmp
#     - ebusrt_data:/data

  fds:
    image: "ebuit:fds"
    volumes:
     - /tmp:/tmp

  ebusrt-listener:
    build: ebusrt-listener
    ports:
     - "8080:8080/udp"
    volumes:
     - /tmp:/tmp
     - /tmp/ipop.json:/tmp/ipop.json
     - ebusrt_data:/data

#  pure-ftpd:
#    image: "stilliard/pure-ftpd:hardened"
#    container_name: ftpd_server
#    ports:
#     - "21:21"
#     - "30000-30009:30000-30009"
#    environment:
#     - "PUBLICHOST=localhost"

# FIX WARNING to be run on HOST
# sysctl vm.overcommit_memory=1
# sysctl -w net.core.somaxconn=1024
# echo never > /sys/kernel/mm/transparent_hugepage/enabled
  redis:
    privileged: true
    image: "redis:alpine"
    ports:
     - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
     - redis_data:/data

  portainer:
    image: "portainer/portainer"
    ports:
     - "9000:9000"
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - portainer_data:/data
