version: '3'
services:

  ebusrt-caller:
    build: ebusrt-caller/Dockerfile
    volumes:
     - /tmp:/tmp

  ebusrt-listener:
    build: ebusrt-listener/Dockerfile
    ports:
     - "8080:8080/udp"
    volumes:
     - /tmp:/tmp
     - ./srt.json: ./srt.json

  pure-ftpd:
    image: "stilliard:pure-ftpd"
  redis:
    image: "redis:alpine"
  portainer:
    image: "portainer:portainer"

