version: '3'

volumes:
  portainer_data:

services:
  ebusrt-caller:
    build: ebusrt-caller
    volumes:
     - /tmp:/tmp

  ebusrt-listener:
    build: ebusrt-listener
    ports:
     - "8080:8080/udp"
    volumes:
     - /tmp:/tmp

  pure-ftpd:
    image: "stilliard/pure-ftpd"
    container_name: ftpd_server
    ports:
     - "21:21"
     - "30000-30009:30000-30009"

  redis:
    image: "redis:alpine"
  portainer:
    image: "portainer/portainer"
    ports:
     - "9000:9000"
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - portainer_data:/data
